version: '3.8'

services:
  # Naš API servis
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=studysphere_db;Username=postgres;Password=${POSTGRES_PASSWORD}
    depends_on:
      - db

  # Naš servis za bazu podataka
  db:
    image: postgres:15 # Koristimo službenu PostgreSQL sliku, verzija 15
    restart: always
    environment:
      - POSTGRES_DB=studysphere_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Opcionalno: ako želiš spajati se na bazu izvana (npr. pgAdminom)